const basePath = process.env.NEXT_PUBLIC_BASE_PATH ?? '';

export const portfolioFilters = ['All', 'Beauty', 'Fashion', 'Jewellery', 'Food', 'Ecommerce', 'Local Brands', 'Creators', 'Startups', 'Fitness', 'Luxury'] as const;

export const portfolioAssets = [
  {
    title: 'Skincare Brands',
    filter: 'Beauty',
    create: 'We create luxury skincare visuals, product reels, and ingredient-story ads.',
    bestFor: 'Best for skincare launches, D2C beauty brands, and product pages.',
    image: `${basePath}/images/video-posters/portfolio-skincare.jpg`,
    video: `${basePath}/video/portfolio/portfolio-skincare.mp4`,
    videoWebm: `${basePath}/video/portfolio/portfolio-skincare.webm`,
    gradient: 'from-cyan-200/18 via-black/10 to-fuchsia-500/14',
  },
  {
    title: 'Cosmetics Brands',
    filter: 'Beauty',
    create: 'We create makeup ads, beauty launch reels, and social campaign visuals.',
    bestFor: 'Best for makeup drops, beauty offers, and Instagram campaigns.',
    image: `${basePath}/images/video-posters/portfolio-cosmetics.jpg`,
    video: `${basePath}/video/portfolio/portfolio-cosmetics.mp4`,
    videoWebm: `${basePath}/video/portfolio/portfolio-cosmetics.webm`,
    gradient: 'from-fuchsia-400/18 via-black/10 to-violet-300/12',
  },
  {
    title: 'Jewellery Brands',
    filter: 'Jewellery',
    create: 'We create jewellery glow shots, festive ads, and luxury product reels.',
    bestFor: 'Best for jewellery drops, festive promotions, and premium socials.',
    image: `${basePath}/images/video-posters/portfolio-jewellery.jpg`,
    video: `${basePath}/video/portfolio/portfolio-jewellery.mp4`,
    videoWebm: `${basePath}/video/portfolio/portfolio-jewellery.webm`,
    gradient: 'from-amber-200/18 via-black/10 to-fuchsia-400/14',
  },
  {
    title: 'Fashion Brands',
    filter: 'Fashion',
    create: 'We create model-led fashion visuals, lookbook reels, and campaign ads.',
    bestFor: 'Best for collections, launches, editorials, and social campaigns.',
    image: `${basePath}/images/video-posters/portfolio-fashion-brands.jpg`,
    video: `${basePath}/video/portfolio/portfolio-fashion-brands.mp4`,
    videoWebm: `${basePath}/video/portfolio/portfolio-fashion-brands.webm`,
    gradient: 'from-violet-400/16 via-black/10 to-cyan-300/14',
  },
  {
    title: 'Clothing Boutiques',
    filter: 'Fashion',
    create: 'We create boutique collection reels, sale creatives, and outfit campaigns.',
    bestFor: 'Best for boutiques, seasonal drops, offers, and Instagram selling.',
    image: `${basePath}/images/video-posters/portfolio-clothing-boutiques.jpg`,
    video: `${basePath}/video/portfolio/portfolio-clothing-boutiques.mp4`,
    videoWebm: `${basePath}/video/portfolio/portfolio-clothing-boutiques.webm`,
    gradient: 'from-fuchsia-300/16 via-black/10 to-cyan-300/12',
  },
  {
    title: 'Ecommerce Sellers',
    filter: 'Ecommerce',
    create: 'We create marketplace visuals, product commercials, and ad creatives.',
    bestFor: 'Best for Amazon, Flipkart, D2C products, and paid ads.',
    image: `${basePath}/images/video-posters/portfolio-luxury-product.jpg`,
    video: `${basePath}/video/portfolio/portfolio-luxury-product.mp4`,
    videoWebm: `${basePath}/video/portfolio/portfolio-luxury-product.webm`,
    gradient: 'from-cyan-300/16 via-black/10 to-white/10',
  },
  {
    title: 'Perfume Brands',
    filter: 'Luxury',
    create: 'We create moody perfume films, launch visuals, and premium bottle shots.',
    bestFor: 'Best for fragrance launches, gifting campaigns, and luxury socials.',
    image: `${basePath}/images/video-posters/portfolio-perfume-brands.jpg`,
    video: `${basePath}/video/portfolio/portfolio-perfume-brands.mp4`,
    videoWebm: `${basePath}/video/portfolio/portfolio-perfume-brands.webm`,
    gradient: 'from-violet-300/16 via-black/10 to-fuchsia-400/14',
  },
  {
    title: 'Luxury Products',
    filter: 'Luxury',
    create: 'We create cinematic product detail shots, hero ads, and brand visuals.',
    bestFor: 'Best for watches, gifting, premium accessories, and launch pages.',
    image: `${basePath}/images/video-posters/portfolio-luxury-products.jpg`,
    video: `${basePath}/video/portfolio/portfolio-luxury-products.mp4`,
    videoWebm: `${basePath}/video/portfolio/portfolio-luxury-products.webm`,
    gradient: 'from-white/14 via-black/10 to-cyan-300/12',
  },
  {
    title: 'Food Brands',
    filter: 'Food',
    create: 'We create food reels, menu visuals, festive offers, and product ads.',
    bestFor: 'Best for packaged food, cloud kitchens, offers, and launches.',
    image: `${basePath}/images/video-posters/portfolio-food-brands.jpg`,
    video: `${basePath}/video/portfolio/portfolio-food-brands.mp4`,
    videoWebm: `${basePath}/video/portfolio/portfolio-food-brands.webm`,
    gradient: 'from-amber-300/18 via-black/10 to-fuchsia-400/12',
  },
  {
    title: 'Cafes & Restaurants',
    filter: 'Food',
    create: 'We create ambience reels, opening launch ads, and offer creatives.',
    bestFor: 'Best for cafes, restaurants, local launches, and promotions.',
    image: `${basePath}/images/video-posters/portfolio-restaurant.jpg`,
    video: `${basePath}/video/portfolio/portfolio-restaurant.mp4`,
    videoWebm: `${basePath}/video/portfolio/portfolio-restaurant.webm`,
    gradient: 'from-cyan-200/14 via-black/10 to-amber-200/12',
  },
  {
    title: 'Influencers & Creators',
    filter: 'Creators',
    create: 'We create personal brand reels, cinematic intros, and profile visuals.',
    bestFor: 'Best for creators, coaches, founders, and premium personal brands.',
    image: `${basePath}/images/video-posters/portfolio-influencers-creators.jpg`,
    video: `${basePath}/video/portfolio/portfolio-influencers-creators.mp4`,
    videoWebm: `${basePath}/video/portfolio/portfolio-influencers-creators.webm`,
    gradient: 'from-fuchsia-400/16 via-black/10 to-cyan-300/14',
  },
  {
    title: 'Startup Launches',
    filter: 'Startups',
    create: 'We create launch teasers, website banners, and founder campaign visuals.',
    bestFor: 'Best for new products, apps, landing pages, and launch offers.',
    image: `${basePath}/images/video-posters/portfolio-neon-brand.jpg`,
    video: `${basePath}/video/portfolio/portfolio-neon-brand.mp4`,
    videoWebm: `${basePath}/video/portfolio/portfolio-neon-brand.webm`,
    gradient: 'from-cyan-300/16 via-black/10 to-violet-300/12',
  },
  {
    title: 'Gyms & Fitness Studios',
    filter: 'Fitness',
    create: 'We create fitness reels, transformation ads, and cinematic workout visuals.',
    bestFor: 'Best for gyms, trainers, yoga studios, and wellness brands.',
    image: `${basePath}/images/video-posters/portfolio-fitness.jpg`,
    video: `${basePath}/video/portfolio/portfolio-fitness.mp4`,
    videoWebm: `${basePath}/video/portfolio/portfolio-fitness.webm`,
    gradient: 'from-emerald-300/16 via-black/10 to-cyan-300/14',
  },
  {
    title: 'Home Decor & Furniture',
    filter: 'Local Brands',
    create: 'We create room-style visuals, product reels, and premium catalogue ads.',
    bestFor: 'Best for furniture stores, decor brands, and home product launches.',
    image: `${basePath}/images/video-posters/portfolio-restaurant.jpg`,
    video: `${basePath}/video/portfolio/portfolio-restaurant.mp4`,
    videoWebm: `${basePath}/video/portfolio/portfolio-restaurant.webm`,
    gradient: 'from-amber-200/14 via-black/10 to-cyan-200/12',
  },
  {
    title: 'Real Estate & Interiors',
    filter: 'Local Brands',
    create: 'We create cinematic interiors, property teasers, and walkthrough-style ads.',
    bestFor: 'Best for interiors, studios, real estate launches, and premium spaces.',
    image: `${basePath}/images/video-posters/portfolio-restaurant.jpg`,
    video: `${basePath}/video/portfolio/portfolio-restaurant.mp4`,
    videoWebm: `${basePath}/video/portfolio/portfolio-restaurant.webm`,
    gradient: 'from-cyan-200/12 via-black/10 to-white/10',
  },
  {
    title: 'Events & Wedding Brands',
    filter: 'Local Brands',
    create: 'We create event promos, wedding brand reels, and festive campaign visuals.',
    bestFor: 'Best for planners, decorators, venues, makeup artists, and studios.',
    image: `${basePath}/images/video-posters/portfolio-events-wedding-brands.jpg`,
    video: `${basePath}/video/portfolio/portfolio-events-wedding-brands.mp4`,
    videoWebm: `${basePath}/video/portfolio/portfolio-events-wedding-brands.webm`,
    gradient: 'from-fuchsia-300/16 via-black/10 to-amber-200/14',
  },
  {
    title: 'Electronics & Gadgets',
    filter: 'Ecommerce',
    create: 'We create tech product ads, feature reels, and launch visuals.',
    bestFor: 'Best for gadgets, accessories, D2C electronics, and online sellers.',
    image: `${basePath}/images/video-posters/portfolio-neon-brand.jpg`,
    video: `${basePath}/video/portfolio/portfolio-neon-brand.mp4`,
    videoWebm: `${basePath}/video/portfolio/portfolio-neon-brand.webm`,
    gradient: 'from-cyan-300/16 via-black/10 to-violet-300/12',
  },
  {
    title: 'Premium Brand Campaigns',
    filter: 'Luxury',
    create: 'We create full cinematic campaign worlds for premium brand perception.',
    bestFor: 'Best for launches, brand identity, hero campaigns, and repositioning.',
    image: `${basePath}/images/video-posters/portfolio-neon-brand.jpg`,
    video: `${basePath}/video/portfolio/portfolio-neon-brand.mp4`,
    videoWebm: `${basePath}/video/portfolio/portfolio-neon-brand.webm`,
    gradient: 'from-fuchsia-400/16 via-black/10 to-cyan-300/14',
  },
] as const;
