const basePath = process.env.NEXT_PUBLIC_BASE_PATH ?? '';

export const portfolioAssets = [
  {
    title: 'Skincare Brands',
    filter: 'Beauty',
    create: 'Luxury skincare visuals, launch reels, ingredient-story ads, and premium beauty campaigns.',
    why: 'Makes your product look premium, trustworthy, and ready for serious buyers.',
    image: `${basePath}/images/portfolio/portfolio-1.webp`,
    gradient: 'from-cyan-200/18 via-black/10 to-fuchsia-500/14',
  },
  {
    title: 'Cosmetics Brands',
    filter: 'Beauty',
    create: 'Lipstick, perfume, makeup product ads, beauty reels, and social media launch creatives.',
    why: 'Helps beauty products stand out without costly models or studio shoots.',
    image: `${basePath}/images/portfolio/portfolio-2.webp`,
    gradient: 'from-fuchsia-400/18 via-black/10 to-violet-300/12',
  },
  {
    title: 'Jewellery Brands',
    filter: 'Jewellery',
    create: 'Cinematic jewellery glow shots, festive campaigns, luxury product films, and Instagram reels.',
    why: 'Makes jewellery look high-value, polished, and premium online.',
    image: `${basePath}/images/portfolio/portfolio-3.webp`,
    gradient: 'from-amber-200/18 via-black/10 to-fuchsia-400/14',
  },
  {
    title: 'Fashion Brands',
    filter: 'Fashion',
    create: 'AI fashion model visuals, clothing launch reels, lookbook campaigns, and editorial-style ads.',
    why: 'Shows your collection with premium styling and campaign-level presentation.',
    image: `${basePath}/images/portfolio/portfolio-4.webp`,
    gradient: 'from-violet-400/16 via-black/10 to-cyan-300/14',
  },
  {
    title: 'Clothing Boutiques',
    filter: 'Fashion',
    create: 'Boutique collection reels, festive outfit campaigns, sale creatives, and Instagram visuals.',
    why: 'Promotes outfits quickly without expensive models, locations, or full shoots.',
    image: `${basePath}/images/portfolio/portfolio-5.webp`,
    gradient: 'from-fuchsia-300/16 via-black/10 to-cyan-300/12',
  },
  {
    title: 'Ecommerce Products',
    filter: 'Ecommerce',
    create: 'Product commercials, marketplace visuals, social ads, banners, and launch creatives.',
    why: 'Turns ordinary product listings into premium brand-style campaigns.',
    image: `${basePath}/images/portfolio/portfolio-6.webp`,
    gradient: 'from-cyan-300/16 via-black/10 to-white/10',
  },
  {
    title: 'Perfume & Luxury Products',
    filter: 'Beauty',
    create: 'Moody cinematic product films, premium brand stories, and high-end launch visuals.',
    why: 'Builds a luxury feeling around products that depend on perception and desire.',
    image: `${basePath}/images/portfolio/portfolio-1.webp`,
    gradient: 'from-violet-300/16 via-black/10 to-fuchsia-400/14',
  },
  {
    title: 'Food Brands & Restaurants',
    filter: 'Food',
    create: 'Food reels, menu promotions, restaurant launch ads, and festive offer creatives.',
    why: 'Makes food look tempting and improves engagement on social platforms.',
    image: `${basePath}/images/portfolio/portfolio-2.webp`,
    gradient: 'from-amber-300/18 via-black/10 to-fuchsia-400/12',
  },
  {
    title: 'Cafes & Local Brands',
    filter: 'Food',
    create: 'Ambience reels, cafe promotions, opening launch campaigns, and stylish local ads.',
    why: 'Gives local brands a polished, premium digital presence customers notice.',
    image: `${basePath}/images/portfolio/portfolio-3.webp`,
    gradient: 'from-cyan-200/14 via-black/10 to-amber-200/12',
  },
  {
    title: 'Influencers & Creators',
    filter: 'Creators',
    create: 'Personal brand reels, cinematic intros, profile visuals, and content campaign assets.',
    why: 'Makes your personal brand look sharper, more premium, and memorable.',
    image: `${basePath}/images/portfolio/portfolio-4.webp`,
    gradient: 'from-fuchsia-400/16 via-black/10 to-cyan-300/14',
  },
  {
    title: 'Startup Product Launches',
    filter: 'Startups',
    create: 'Product teaser films, launch visuals, website banners, and social campaign creatives.',
    why: 'Helps new products look credible, exciting, and ready for launch.',
    image: `${basePath}/images/portfolio/portfolio-5.webp`,
    gradient: 'from-cyan-300/16 via-black/10 to-violet-300/12',
  },
  {
    title: 'Premium Brand Campaigns',
    filter: 'Startups',
    create: 'Full cinematic campaign worlds for brands that want luxury perception and strong visual identity.',
    why: 'Creates a high-end brand image across ads, reels, and launch visuals.',
    image: `${basePath}/images/portfolio/portfolio-6.webp`,
    gradient: 'from-fuchsia-400/16 via-black/10 to-cyan-300/14',
  },
] as const;
